### ISSUE TITLE
Nothing is happening after changing search parameters

### ISSUE THREAD

**Issue by unlight** [tannerlinsley/react-location#180]
**Describe the bug**
Changing search parameters is not triggering navigation, no loader calls.

**To Reproduce**
1. Go to https://codesandbox.io/s/adoring-williamson-9y8e6?file=/src/index.tsx
2. Click on page 1 link
3. Click on page 2 link
4. No new posts from page 2

**Expected behavior**
New posts from page 2.
This steps are working without issues.
1. Click on page 1 link
2. Click on home link
3. Click on page 2 link
4. Posts 6-10 are shown

**Additional context**
This steps are working without issues.
1. Click on page 1 link
2. Click on home link
3. Click on page 2 link
4. Posts 6-10 are shown

**Env:**
- Browser: chrome (latest)
- Lib version 3.3.0

**Comment by joshuabrokaw** [comment]
Check out the documentation for [Route Loaders](https://react-location.tanstack.com/guides/route-loaders)

It says...

Route loaders are called when:
- A route is matched for navigation
- A route is matched for preloading

the search param is not part of the matched route, so when you click the link, the route is already matched and already loaded. I'd suggest using 

`const { page } = useSearch<MyLocationGenerics>()`

and then fetching the data in the component instead of in the router

**Comment by tannerlinsley** [comment]
Thanks @joshuabrokaw 👍
